# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Moodly2.0' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  # Pods for Moodly2.0

  #Pods for Moodly App 2.0
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

end
